### ISSUE TITLE
Wrong dependencies with perceval in setup.py

### ISSUE THREAD

**Issue by acs** [chaoss/grimoirelab-kingarthur#26]
In setup.py only perceval dependency is defined but arthur also needs:

* perceval-mozilla
* perceval-opnfv
* perceval-puppet (this pip package does not exists yet)

**Comment by jgbarah** [comment]
I think this can be solved in two different ways:

* Modify setup.py for adding those dependencies
* Modify kingarthur so that it can work without those dependencies, so that they can be really recommended and not hard dependencies.

I would prefer the second way, because most users really don't need those packages. But I know it is maybe more difficult to implement.

If you prefer the first one, I can implement it.

WRT the pacackage for perceval-puppet, I've opened chaoss/grimoirelab-perceval-puppet#10

**Comment by sduenas** [comment]
This is not an issue anymore.
